'use strict';String.prototype.hashCode=function(){var b=0,a=null,c=null,d=null;if(0!=this.length){a=0;for(d=this.length;a<d;a++)c=this.charCodeAt(a),b=(b<<5)-b+c,b|=0}return b};function GSProfileEmailSettingsMessage(b){this.messageBox=document.querySelector(b);this.OK="";this.ERROR="alert-error";this.SUCCESS="alert-success";this.INFO="alert-info"}GSProfileEmailSettingsMessage.prototype.clearMessage=function(){for(;this.messageBox.firstChild;)this.messageBox.removeChild(this.messageBox.firstChild)};
GSProfileEmailSettingsMessage.prototype.setMessage=function(b,a){var c=null,d=null,d=null,c=document.createElement("div");c.setAttribute("class","alert alert-block fade in"+a);d=document.createElement("button");d.setAttribute("type","button");d.setAttribute("class","close");d.setAttribute("data-dismiss","alert");d.textContent="×";c.appendChild(d);d=document.createElement("div");d.innerHTML=b;c.appendChild(d);this.messageBox.appendChild(c)};
GSProfileEmailSettingsMessage.prototype.display=function(b,a){var c=null,c="undefined"!==typeof a?" "+a:this.OK;this.clearMessage();this.setMessage(b,c);window.scrollTo(0,0)};
function GSProfileEmailSettingsAJAX(){function b(a,b,c){function d(b,c){var f=null,f=new XMLHttpRequest;"undefined"!==typeof b&&f.addEventListener("load",b);"undefined"!==typeof c&&f.addEventListener("error",c);f.open("POST",a);return f}return{send:function(a,v,n){var r=null,m=null,m=new FormData;m.append(b,c);m.append("email",a);r=new d(v,n);r.send(m)}}}var a=null,c=null,d=null,n=null,s=null,a=new b("gs-profile-email-settings-delete.json","delete","Delete"),c=new b("gs-profile-email-settings-prefer.json",
"prefer","Prefer"),d=new b("gs-profile-email-settings-demote.json","demote","Demote"),n=new b("gs-profile-email-settings-resend.json","resend","Resend"),s=new b("gs-profile-email-settings-add.json","add","Add");return{remove:function(b,c,d){a.send(b,c,d)},prefer:function(a,b,d){c.send(a,b,d)},demote:function(a,b,c){d.send(a,b,c)},resend:function(a,b,c){n.send(a,b,c)},add:function(a,b,c){s.send(a,b,c)},status:function(a){var b=null,b=new XMLHttpRequest;"undefined"!==typeof b&&b.addEventListener("load",
a);b.open("GET","gs-profile-email-settings-status.json");b.send()}}}function GSProfileEmailSettingsRemoveEvent(b){var a=document.createEvent("CustomEvent");a.initCustomEvent("GSProfileEmailSettingsRemove",!0,!0,b);return a}function GSProfileEmailDragStart(b){var a=document.createEvent("CustomEvent");a.initCustomEvent("GSProfileEmailDragStart",!0,!0,b);return a}function GSProfileEmailDragEnd(b){var a=document.createEvent("CustomEvent");a.initCustomEvent("GSProfileEmailDragEnd",!0,!0,b);return a}
function GSProfileEmailSettingsArea(b,a){this.elem=b;this.list=b.getElementsByTagName("ul")[0];this.model=a;this.addrs=null}GSProfileEmailSettingsArea.prototype.findItem=function(b){for(var a=null,a=b;null!=a&&"li"!=a.tagName.toLowerCase();)a=a.parentElement;return a};GSProfileEmailSettingsArea.prototype.show=function(){this.elem.hasAttribute("style")&&this.elem.removeAttribute("style");this.elem.hasAttribute("aria-hidden")&&this.elem.removeAttribute("aria-hidden")};
GSProfileEmailSettingsArea.prototype.hide=function(){this.elem.setAttribute("style","display:none;");this.elem.setAttribute("aria-hidden","true")};GSProfileEmailSettingsArea.prototype.clear=function(){for(this.addrs=null;this.list.firstChild;)this.list.removeChild(this.list.firstChild)};GSProfileEmailSettingsArea.prototype.updateAddrs=function(){var b=0,a=null;for(b in this.addrs)a=this.createItem(this.addrs[b]),this.list.appendChild(a)};
GSProfileEmailSettingsArea.prototype.emailFromEvent=function(b){var a=null,a=a=null,a=b.target,a=this.findItem(a);return a=a.querySelector("code.email").textContent};GSProfileEmailSettingsArea.prototype.removeClicked=function(b){var a=null,a=null,a=this.emailFromEvent(b),a=GSProfileEmailSettingsRemoveEvent({email:a});b.target.dispatchEvent(a)};
GSProfileEmailSettingsArea.prototype.isAddr=function(b){for(var a=!1,c=0;c<b.dataTransfer.types.length;++c)"application/x-gs-address"===b.dataTransfer.types[c]&&(a=!0);return a};GSProfileEmailSettingsArea.prototype.dragStart=function(b){var a=null,a=null,a=this.emailFromEvent(b);b.dataTransfer.setData("application/x-gs-address",a);b.dataTransfer.effectAllowed="move";a=GSProfileEmailDragStart();b.target.dispatchEvent(a)};
GSProfileEmailSettingsArea.prototype.dragOver=function(b){var a=null;this.isAddr(b)&&(a=b.dataTransfer.getData("application/x-gs-address"),-1==this.addrs.indexOf(a)&&b.preventDefault())};GSProfileEmailSettingsArea.prototype.dropPrepare=function(){var b="",b=this.list.className;-1==b.indexOf("drop-prepare")&&(this.list.className=b+" drop-prepare")};
GSProfileEmailSettingsArea.prototype.clearDropPrepare=function(){var b="",a=0,b=this.list.className,a=b.indexOf(" drop-prepare");-1!=a&&(this.list.className=b.slice(0,a)+b.slice(a+13))};GSProfileEmailSettingsArea.prototype.dragEnd=function(b){var a=null,a=GSProfileEmailDragEnd();b.target.dispatchEvent(a)};function GSProfileEmailSettingsPreferEvent(b){var a=document.createEvent("CustomEvent");a.initCustomEvent("GSProfileEmailSettingsPrefer",!0,!0,b);return a}
function GSProfileEmailSettingsDemoteEvent(b){var a=document.createEvent("CustomEvent");a.initCustomEvent("GSProfileEmailSettingsDemote",!0,!0,b);return a}function GSProfileEmailSettingsPreferred(b,a){GSProfileEmailSettingsArea.call(this,b,a);b.addEventListener("dragover",this.dragOver.bind(this));b.addEventListener("drop",this.drop.bind(this));b.addEventListener("dragend",this.dragEnd.bind(this))}GSProfileEmailSettingsPreferred.prototype=Object.create(GSProfileEmailSettingsArea.prototype);
GSProfileEmailSettingsPreferred.prototype.constructor=GSProfileEmailSettingsPreferred;GSProfileEmailSettingsPreferred.prototype.demoteClicked=function(b){var a=null,a=null,a=this.emailFromEvent(b),a=GSProfileEmailSettingsDemoteEvent({email:a});b.target.dispatchEvent(a)};GSProfileEmailSettingsPreferred.prototype.drop=function(b){var a=null,a=null;b.preventDefault();a=b.dataTransfer.getData("application/x-gs-address");a=GSProfileEmailSettingsPreferEvent({email:a});b.target.dispatchEvent(a)};
GSProfileEmailSettingsPreferred.prototype.createItem=function(b,a){var c=null,d=null,c=this.model.querySelector(".preferred-address").cloneNode(!0);c.setAttribute("id","email"+b.hashCode());d=c.querySelector(".email");d.textContent=b;a?(c.querySelector(".demote").addEventListener("click",this.demoteClicked.bind(this)),c.querySelector(".remove").addEventListener("click",this.removeClicked.bind(this)),d.setAttribute("draggable","true"),d.addEventListener("dragstart",this.dragStart.bind(this))):(toolbar=
c.querySelector('[role="toolbar"]'),c.removeChild(toolbar));return c};GSProfileEmailSettingsPreferred.prototype.update=function(b){var a=null,c=!1,d=0;this.clear();this.addrs=b.preferred;c=1<this.addrs.length;for(d in this.addrs)a=this.createItem(this.addrs[d],c),this.list.appendChild(a)};
function GSProfileEmailSettingsExtra(b,a){GSProfileEmailSettingsArea.call(this,b,a);b.addEventListener("dragover",this.dragOver.bind(this));b.addEventListener("drop",this.drop.bind(this));b.addEventListener("dragend",this.dragEnd.bind(this))}GSProfileEmailSettingsExtra.prototype=Object.create(GSProfileEmailSettingsArea.prototype);GSProfileEmailSettingsExtra.prototype.constructor=GSProfileEmailSettingsExtra;
GSProfileEmailSettingsExtra.prototype.preferClicked=function(b){var a=null,a=null,a=this.emailFromEvent(b),a=GSProfileEmailSettingsPreferEvent({email:a});b.target.dispatchEvent(a)};GSProfileEmailSettingsExtra.prototype.drop=function(b){var a=null,a=null;b.preventDefault();a=b.dataTransfer.getData("application/x-gs-address");a=GSProfileEmailSettingsDemoteEvent({email:a});b.target.dispatchEvent(a)};
GSProfileEmailSettingsExtra.prototype.createItem=function(b){var a=null,c=null,a=this.model.querySelector(".extra-address").cloneNode(!0);a.setAttribute("id","email"+b.hashCode());c=a.querySelector(".email");c.textContent=b;c.addEventListener("dragstart",this.dragStart.bind(this));a.querySelector(".prefer").addEventListener("click",this.preferClicked.bind(this));a.querySelector(".remove").addEventListener("click",this.removeClicked.bind(this));return a};
GSProfileEmailSettingsExtra.prototype.update=function(b){this.clear();this.addrs=b.other;this.updateAddrs();this.clearDropPrepare()};function GSProfileEmailSettingsResendEvent(b){var a=document.createEvent("CustomEvent");a.initCustomEvent("GSProfileEmailSettingsResend",!0,!0,b);return a}function GSProfileEmailSettingsUnverified(b,a){GSProfileEmailSettingsArea.call(this,b,a)}GSProfileEmailSettingsUnverified.prototype=Object.create(GSProfileEmailSettingsArea.prototype);
GSProfileEmailSettingsUnverified.prototype.constructor=GSProfileEmailSettingsUnverified;GSProfileEmailSettingsArea.prototype.verifyClicked=function(b){var a=null,a=null,a=this.emailFromEvent(b),a=GSProfileEmailSettingsResendEvent({email:a});b.target.dispatchEvent(a)};
GSProfileEmailSettingsUnverified.prototype.createItem=function(b){var a=null,a=this.model.querySelector(".unverified-address").cloneNode(!0);a.setAttribute("id","email"+b.hashCode());a.querySelector(".email").textContent=b;a.querySelector(".verify").addEventListener("click",this.verifyClicked.bind(this));a.querySelector(".remove").addEventListener("click",this.removeClicked.bind(this));return a};GSProfileEmailSettingsUnverified.prototype.update=function(b){this.clear();this.addrs=b.unverified;this.updateAddrs()};
function GSProfileEmailSettingsAddEvent(b){var a=document.createEvent("CustomEvent");a.initCustomEvent("GSProfileEmailSettingsAdd",!0,!0,b);return a}function GSProfileEmailSettingsAdd(b){this.elem=b;this.input=b.getElementsByTagName("input")[0];this.input.addEventListener("keyup",this.inputChanged.bind(this));this.button=b.getElementsByTagName("button")[0];this.button.setAttribute("disabled","disabled");this.button.addEventListener("click",this.addClicked.bind(this))}
GSProfileEmailSettingsAdd.prototype.inputChanged=function(b){0<this.input.value.length&&this.button.hasAttribute("disabled")&&(!("validity"in this.input)||this.input.validity.valid)?this.button.removeAttribute("disabled"):"Enter"==b.key&&!this.button.hasAttribute("disabled")?this.button.click():(!this.button.hasAttribute("disabled")&&0==this.input.value.length||"validity"in this.input&&!this.input.validity.valid)&&this.button.setAttribute("disabled","disabled")};
GSProfileEmailSettingsAdd.prototype.addClicked=function(b){var a=null;this.input.setAttribute("disabled","disabled");a=GSProfileEmailSettingsAddEvent({email:this.input.value});b.target.dispatchEvent(a)};GSProfileEmailSettingsAdd.prototype.reset=function(){this.input.value="";this.input.removeAttribute("disabled")};
function GSProfileEmailSettingsUpdate(b,a,c,d,n,s,v){function f(b,a){var c=null,d=null,c=null,c=z.getElementsByClassName(b)[0],d=c.cloneNode(!0),c=c.getElementsByClassName("email")[0];c.textContent=a;return d.innerHTML}function q(b){g.display(b)}function B(b){var a=null,a=JSON.parse(b.target.responseText);w(a)}function w(b){k.update(b);p.update(b);t.update(b);0<b.unverified.length?t.show():t.hide();0<b.preferred.length?k.show():0==b.preferred.length&&0<b.other.length?k.show():k.hide();0<b.other.length||
1<b.preferred.length?p.show():p.hide()}function x(b){var a="",a="",a=b.detail.email,a=f("removing",a);e=window.setTimeout(q,100,a);l.remove(b.detail.email,u)}function y(b){var a="",a="",a=b.detail.email,a=f("preferring",a);e=window.setTimeout(q,100,a);l.prefer(b.detail.email,u)}function r(b){var a="",a="",a=b.detail.email,a=f("extra",a);e=window.setTimeout(q,100,a);l.demote(b.detail.email,u)}function m(b){var a="",c="",a=b.detail.email,c=f("resend",a);e=window.setTimeout(q,100,c);l.resend(a,u)}function u(b){var a=
null,a="";window.clearTimeout(e);e=null;200==this.status?(a=JSON.parse(b.target.responseText),0==a.status?(g.display(a.message),w(a.email)):g.display(a.message[0],g.INFO)):(a="There was a problem: "+this.statusText+" ("+this.status+").",g.display(a,g.ERROR))}function C(a){var b="",c="",b=a.detail.email,c=f("adding",b);e=window.setTimeout(q,100,c);l.add(b,D,E)}function D(a){a=null;a="";window.clearTimeout(e);e=null;200==this.status?(a=JSON.parse(this.responseText),0==a.status?(g.display(a.message,
g.SUCCESS),w(a.email)):g.display(a.message[0],g.INFO)):(a="There was a problem: "+this.statusText+" ("+this.status+").",g.display(a,g.ERROR));A.reset()}function E(a){window.clearTimeout(e);e=null;console.log("Issues");g.display("Issues",g.ERROR)}var l=null,k=null,p=null,t=null,g=null,z=null,A=null,e=null;(function(){var h=null,f=null,e=h=null,e=null;g=new GSProfileEmailSettingsMessage(s);e=document.querySelector(n);z=document.querySelector(v);h=document.querySelector(b);h.addEventListener("GSProfileEmailSettingsRemove",
x);h.addEventListener("GSProfileEmailSettingsPrefer",y);h.addEventListener("GSProfileEmailSettingsDemote",r);k=new GSProfileEmailSettingsPreferred(h,e);f=document.querySelector(a);f.addEventListener("GSProfileEmailSettingsRemove",x);f.addEventListener("GSProfileEmailSettingsPrefer",y);f.addEventListener("GSProfileEmailSettingsDemote",r);p=new GSProfileEmailSettingsExtra(f,e);h.addEventListener("GSProfileEmailDragStart",function(a){p.dropPrepare()});h.addEventListener("GSProfileEmailDragEnd",function(a){p.clearDropPrepare()});
f.addEventListener("GSProfileEmailDragStart",function(a){k.dropPrepare()});f.addEventListener("GSProfileEmailDragEnd",function(a){k.clearDropPrepare()});h=document.querySelector(c);h.addEventListener("GSProfileEmailSettingsRemove",x);h.addEventListener("GSProfileEmailSettingsResend",m);t=new GSProfileEmailSettingsUnverified(h,e);e=document.querySelector(d);A=new GSProfileEmailSettingsAdd(e);e.addEventListener("GSProfileEmailSettingsAdd",C);l=new GSProfileEmailSettingsAJAX;l.status(B)})()}
window.addEventListener("load",function(b){b=null;b=document.getElementById("gs-profile-email-settings-script");GSProfileEmailSettingsUpdate(b.getAttribute("data-preferred"),b.getAttribute("data-extra"),b.getAttribute("data-unverified"),b.getAttribute("data-add"),b.getAttribute("data-model"),b.getAttribute("data-messagebox"),b.getAttribute("data-feedback"))});
