'use strict';String.prototype.hashCode=function(){var a=0,c=null,l=null,h=null;if(0!=this.length){c=0;for(h=this.length;c<h;c++)l=this.charCodeAt(c),a=(a<<5)-a+l,a|=0}return a};
function GSProfileEmailSettingsMessage(a){var c=null,c=document.querySelector(a);return{display:function(a,h){for(var k=null,k="undefined"!==typeof h?" "+h:"";c.firstChild;)c.removeChild(c.firstChild);var d=null,g=null,g=null,d=document.createElement("div");d.setAttribute("class","alert alert-block fade in"+k);g=document.createElement("button");g.setAttribute("type","button");g.setAttribute("class","close");g.setAttribute("data-dismiss","alert");g.textContent="×";d.appendChild(g);g=document.createElement("div");
g.innerHTML=a;d.appendChild(g);c.appendChild(d)},OK:"",ERROR:"alert-error",SUCCESS:"alert-success",INFO:"alert-info"}}
function GSProfileEmailSettingsUpdate(a,c,l,h,k){function d(e){for(var b=null,b=e;null!=b&&"li"!=b.tagName.toLowerCase();)b=b.parentElement;return b}function g(e){var b=null,f=b=b=null,a=null,b=e.target,b=d(b),b=b.querySelector("code.email").textContent,f=new FormData;f.append("email",b);f.append("delete","Delete");a=new XMLHttpRequest;a.addEventListener("load",m);a.open("POST",p.delete);a.send(f);console.log(b)}function m(e){e=null;e=JSON.parse(this.responseText);q.display(e.message);n(e.email)}
function x(e){var b=null,f=b=null,f=b=null,b=e.target,b=d(b),f=b.querySelector("code.email").textContent,b=new FormData;b.append("email",f);b.append("prefer","Prefer");f=new XMLHttpRequest;f.addEventListener("load",y);f.open("POST",p.prefer);f.send(b)}function y(e){e=null;e=JSON.parse(this.responseText);q.display(e.message);n(e.email)}function z(e){var b=null,f=b=null,f=b=null,b=e.target,b=d(b),f=b.querySelector("code.email").textContent,b=new FormData;b.append("email",f);b.append("demote","Demote");
f=new XMLHttpRequest;f.addEventListener("load",A);f.open("POST",p.demote);f.send(b)}function A(e){e=null;e=JSON.parse(this.responseText);q.display(e.message);n(e.email)}function B(e){var b=null,f=b=null,f=b=null,b=e.target,b=d(b),f=b.querySelector("code.email").textContent,b=new FormData;b.append("email",f);b.append("resend","Resend");f=new XMLHttpRequest;f.addEventListener("load",C);f.open("POST",p.resend);f.send(b)}function C(e){e=null;e=JSON.parse(this.responseText);n(e.email)}function s(e){for(;e.firstChild;)e.removeChild(e.firstChild)}
function n(e){s(t.querySelector("ul"));s(u.querySelector("ul"));s(v.querySelector("ul"));w=null;var b=e.preferred,f=0,a=null,c=!1,d=null,d=t.getElementsByTagName("ul")[0],c=1<b.length;for(f in b){var a=b[f],l=c,h=null,k=null,h=r.querySelector(".preferred-address").cloneNode(!0);h.setAttribute("id","email"+a.hashCode());h.querySelector(".email").textContent=a;l?(h.querySelector(".demote").addEventListener("click",z),h.querySelector(".remove").addEventListener("click",g)):(k=h.querySelector('[role="toolbar"]'),
h.removeChild(k));a=h;d.appendChild(a)}b=e.other;f=0;c=d=null;c=u.getElementsByTagName("ul")[0];for(f in b)d=b[f],a=null,a=r.querySelector(".extra-address").cloneNode(!0),a.setAttribute("id","email"+d.hashCode()),a.querySelector(".email").textContent=d,a.querySelector(".prefer").addEventListener("click",x),a.querySelector(".remove").addEventListener("click",g),d=a,c.appendChild(d);e=e.unverified;b=0;f=c=null;f=v.getElementsByTagName("ul")[0];for(b in e)c=e[b],d=null,d=r.querySelector(".unverified-address").cloneNode(!0),
d.setAttribute("id","email"+c.hashCode()),d.querySelector(".email").textContent=c,d.querySelector(".verify").addEventListener("click",B),d.querySelector(".remove").addEventListener("click",g),c=d,f.appendChild(c)}var r=null,t=null,u=null,v=null,w=null,q=null,p={"delete":"gs-profile-email-settings-delete.json",prefer:"gs-profile-email-settings-prefer.json",demote:"gs-profile-email-settings-demote.json",resend:"gs-profile-email-settings-resend.json"},r=document.querySelector(a),t=document.querySelector(c),
u=document.querySelector(l),v=document.querySelector(h),q=GSProfileEmailSettingsMessage(k);return{setAddresses:function(a){n(a)},getAddresses:function(){return w}}}
function GSProfileEmailSettingsAdd(a,c,l){function h(a){a=null;a=JSON.parse(this.responseText);m.display(a.message,m.SUCCESS);l.setAddresses(a.email);d.value="";d.removeAttribute("disabled")}var k=null,d=null,g=null,m=null,k=document.querySelector(a),d=k.getElementsByTagName("input")[0];d.addEventListener("keyup",function(a){0<d.value.length&&g.hasAttribute("disabled")&&(!("validity"in d)||d.validity.valid)?g.removeAttribute("disabled"):"Enter"==a.key&&!g.hasAttribute("disabled")?g.click():(!g.hasAttribute("disabled")&&
0==d.value.length||"validity"in d&&!d.validity.valid)&&g.setAttribute("disabled","disabled")});g=k.getElementsByTagName("button")[0];g.setAttribute("disabled","disabled");g.addEventListener("click",function(a){var c=a=null;d.setAttribute("disabled","disabled");c=new FormData;c.append("email",d.value);c.append("add","Add");a=new XMLHttpRequest;a.addEventListener("load",h);a.open("POST","gs-profile-email-settings-add.json");a.send(c)});m=GSProfileEmailSettingsMessage(c)}
function gs_profile_email_settings_load(a){var c=null,c=new XMLHttpRequest;c.addEventListener("load",function(c){c=null;c=JSON.parse(this.responseText);a.setAddresses(c)});c.open("GET","gs-profile-email-settings-status.json");c.send()}
window.addEventListener("load",function(a){var c=a=null;a=document.getElementById("gs-profile-email-settings-script");c=GSProfileEmailSettingsUpdate(a.getAttribute("data-model"),a.getAttribute("data-preferred"),a.getAttribute("data-extra"),a.getAttribute("data-unverified"),a.getAttribute("data-messagebox"));gs_profile_email_settings_load(c);GSProfileEmailSettingsAdd(a.getAttribute("data-add"),a.getAttribute("data-messagebox"),c)});
