'use strict';String.prototype.hashCode=function(){var a=0,b=null,c=null,d=null;if(0!=this.length){b=0;for(d=this.length;b<d;b++)c=this.charCodeAt(b),a=(a<<5)-a+c,a|=0}return a};function GSProfileEmailSettingsMessage(a){this.messageBox=document.querySelector(a);this.OK="";this.ERROR="alert-error";this.SUCCESS="alert-success";this.INFO="alert-info"}GSProfileEmailSettingsMessage.prototype.clearMessage=function(){for(;this.messageBox.firstChild;)this.messageBox.removeChild(this.messageBox.firstChild)};
GSProfileEmailSettingsMessage.prototype.setMessage=function(a,b){var c=null,d=null,d=null,c=document.createElement("div");c.setAttribute("class","alert alert-block fade in"+b);d=document.createElement("button");d.setAttribute("type","button");d.setAttribute("class","close");d.setAttribute("data-dismiss","alert");d.textContent="×";c.appendChild(d);d=document.createElement("div");d.innerHTML=a;c.appendChild(d);this.messageBox.appendChild(c)};
GSProfileEmailSettingsMessage.prototype.display=function(a,b){var c=null,c="undefined"!==typeof b?" "+b:this.OK;this.clearMessage();this.setMessage(a,c)};
function GSProfileEmailSettingsAJAX(){function a(b,a,c){function d(a){var c=null,c=new XMLHttpRequest;"undefined"!==typeof a&&c.addEventListener("load",a);c.open("POST",b);return c}return{send:function(b,r){var e=null,k=null,k=new FormData;k.append(a,c);k.append("email",b);e=new d(r);e.send(k)}}}var b=null,c=null,d=null,l=null,m=null,b=new a("gs-profile-email-settings-delete.json","delete","Delete"),c=new a("gs-profile-email-settings-prefer.json","prefer","Prefer"),d=new a("gs-profile-email-settings-demote.json",
"demote","Demote"),l=new a("gs-profile-email-settings-resend.json","resend","Resend"),m=new a("gs-profile-email-settings-add.json","add","Add");return{remove:function(a,c){b.send(a,c)},prefer:function(b,a){c.send(b,a)},demote:function(b,a){d.send(b,a)},resend:function(b,a){l.send(b,a)},add:function(b,a){m.send(b,a)},status:function(b){var a=null,a=new XMLHttpRequest;"undefined"!==typeof a&&a.addEventListener("load",b);a.open("GET","gs-profile-email-settings-status.json");a.send()}}}
function GSProfileEmailSettingsRemoveEvent(a){var b=document.createEvent("CustomEvent");b.initCustomEvent("GSProfileEmailSettingsRemove",!0,!0,a);return b}function GSProfileEmailDragStart(a){var b=document.createEvent("CustomEvent");b.initCustomEvent("GSProfileEmailDragStart",!0,!0,a);return b}function GSProfileEmailDragEnd(a){var b=document.createEvent("CustomEvent");b.initCustomEvent("GSProfileEmailDragEnd",!0,!0,a);return b}
function GSProfileEmailSettingsArea(a,b){this.elem=a;this.list=a.getElementsByTagName("ul")[0];this.model=b;this.addrs=null}GSProfileEmailSettingsArea.prototype.findItem=function(a){for(var b=null,b=a;null!=b&&"li"!=b.tagName.toLowerCase();)b=b.parentElement;return b};GSProfileEmailSettingsArea.prototype.clear=function(){for(this.addrs=null;this.list.firstChild;)this.list.removeChild(this.list.firstChild)};
GSProfileEmailSettingsArea.prototype.updateAddrs=function(){var a=0,b=null;for(a in this.addrs)b=this.createItem(this.addrs[a]),this.list.appendChild(b)};GSProfileEmailSettingsArea.prototype.emailFromEvent=function(a){var b=null,b=b=null,b=a.target,b=this.findItem(b);return b=b.querySelector("code.email").textContent};GSProfileEmailSettingsArea.prototype.removeClicked=function(a){var b=null,b=null,b=this.emailFromEvent(a),b=GSProfileEmailSettingsRemoveEvent({email:b});a.target.dispatchEvent(b)};
GSProfileEmailSettingsArea.prototype.isAddr=function(a){for(var b=!1,c=0;c<a.dataTransfer.types.length;++c)"application/x-gs-address"===a.dataTransfer.types[c]&&(b=!0);return b};GSProfileEmailSettingsArea.prototype.dragStart=function(a){var b=null,b=null,b=this.emailFromEvent(a);a.dataTransfer.setData("application/x-gs-address",b);a.dataTransfer.effectAllowed="move";b=GSProfileEmailDragStart();a.target.dispatchEvent(b)};
GSProfileEmailSettingsArea.prototype.dragOver=function(a){var b=null;this.isAddr(a)&&(b=a.dataTransfer.getData("application/x-gs-address"),-1==this.addrs.indexOf(b)&&a.preventDefault())};GSProfileEmailSettingsArea.prototype.dropPrepare=function(){var a="",a=this.list.className;-1==a.indexOf("drop-prepare")&&(this.list.className=a+" drop-prepare")};
GSProfileEmailSettingsArea.prototype.clearDropPrepare=function(){var a="",b=0,a=this.list.className,b=a.indexOf(" drop-prepare");-1!=b&&(this.list.className=a.slice(0,b)+a.slice(b+13))};GSProfileEmailSettingsArea.prototype.dragEnd=function(a){var b=null,b=GSProfileEmailDragEnd();a.target.dispatchEvent(b)};function GSProfileEmailSettingsPreferEvent(a){var b=document.createEvent("CustomEvent");b.initCustomEvent("GSProfileEmailSettingsPrefer",!0,!0,a);return b}
function GSProfileEmailSettingsDemoteEvent(a){var b=document.createEvent("CustomEvent");b.initCustomEvent("GSProfileEmailSettingsDemote",!0,!0,a);return b}function GSProfileEmailSettingsPreferred(a,b){GSProfileEmailSettingsArea.call(this,a,b);a.addEventListener("dragover",this.dragOver.bind(this));a.addEventListener("drop",this.drop.bind(this));a.addEventListener("dragend",this.dragEnd.bind(this))}GSProfileEmailSettingsPreferred.prototype=Object.create(GSProfileEmailSettingsArea.prototype);
GSProfileEmailSettingsPreferred.prototype.constructor=GSProfileEmailSettingsPreferred;GSProfileEmailSettingsPreferred.prototype.demoteClicked=function(a){var b=null,b=null,b=this.emailFromEvent(a),b=GSProfileEmailSettingsDemoteEvent({email:b});a.target.dispatchEvent(b)};GSProfileEmailSettingsPreferred.prototype.drop=function(a){var b=null,b=null;a.preventDefault();b=a.dataTransfer.getData("application/x-gs-address");b=GSProfileEmailSettingsPreferEvent({email:b});a.target.dispatchEvent(b)};
GSProfileEmailSettingsPreferred.prototype.createItem=function(a,b){var c=null,d=null,c=this.model.querySelector(".preferred-address").cloneNode(!0);c.setAttribute("id","email"+a.hashCode());d=c.querySelector(".email");d.textContent=a;b?(c.querySelector(".demote").addEventListener("click",this.demoteClicked.bind(this)),c.querySelector(".remove").addEventListener("click",this.removeClicked.bind(this)),d.setAttribute("draggable","true"),d.addEventListener("dragstart",this.dragStart.bind(this))):(toolbar=
c.querySelector('[role="toolbar"]'),c.removeChild(toolbar));return c};GSProfileEmailSettingsPreferred.prototype.update=function(a){var b=null,c=!1,d=0;this.clear();this.addrs=a.preferred;c=1<this.addrs.length;for(d in this.addrs)b=this.createItem(this.addrs[d],c),this.list.appendChild(b)};
function GSProfileEmailSettingsExtra(a,b){GSProfileEmailSettingsArea.call(this,a,b);a.addEventListener("dragover",this.dragOver.bind(this));a.addEventListener("drop",this.drop.bind(this));a.addEventListener("dragend",this.dragEnd.bind(this))}GSProfileEmailSettingsExtra.prototype=Object.create(GSProfileEmailSettingsArea.prototype);GSProfileEmailSettingsExtra.prototype.constructor=GSProfileEmailSettingsExtra;
GSProfileEmailSettingsExtra.prototype.preferClicked=function(a){var b=null,b=null,b=this.emailFromEvent(a),b=GSProfileEmailSettingsPreferEvent({email:b});a.target.dispatchEvent(b)};GSProfileEmailSettingsExtra.prototype.drop=function(a){var b=null,b=null;a.preventDefault();b=a.dataTransfer.getData("application/x-gs-address");b=GSProfileEmailSettingsDemoteEvent({email:b});a.target.dispatchEvent(b)};
GSProfileEmailSettingsExtra.prototype.createItem=function(a){var b=null,c=null,b=this.model.querySelector(".extra-address").cloneNode(!0);b.setAttribute("id","email"+a.hashCode());c=b.querySelector(".email");c.textContent=a;c.addEventListener("dragstart",this.dragStart.bind(this));b.querySelector(".prefer").addEventListener("click",this.preferClicked.bind(this));b.querySelector(".remove").addEventListener("click",this.removeClicked.bind(this));return b};
GSProfileEmailSettingsExtra.prototype.update=function(a){this.clear();this.addrs=a.other;this.updateAddrs();this.clearDropPrepare()};function GSProfileEmailSettingsResendEvent(a){var b=document.createEvent("CustomEvent");b.initCustomEvent("GSProfileEmailSettingsResend",!0,!0,a);return b}function GSProfileEmailSettingsUnverified(a,b){GSProfileEmailSettingsArea.call(this,a,b)}GSProfileEmailSettingsUnverified.prototype=Object.create(GSProfileEmailSettingsArea.prototype);
GSProfileEmailSettingsUnverified.prototype.constructor=GSProfileEmailSettingsUnverified;GSProfileEmailSettingsArea.prototype.verifyClicked=function(a){var b=null,b=null,b=this.emailFromEvent(a),b=GSProfileEmailSettingsResendEvent({email:b});a.target.dispatchEvent(b)};
GSProfileEmailSettingsUnverified.prototype.createItem=function(a){var b=null,b=this.model.querySelector(".unverified-address").cloneNode(!0);b.setAttribute("id","email"+a.hashCode());b.querySelector(".email").textContent=a;b.querySelector(".verify").addEventListener("click",this.verifyClicked.bind(this));b.querySelector(".remove").addEventListener("click",this.removeClicked.bind(this));return b};GSProfileEmailSettingsUnverified.prototype.update=function(a){this.clear();this.addrs=a.unverified;this.updateAddrs()};
function GSProfileEmailSettingsAddEvent(a){var b=document.createEvent("CustomEvent");b.initCustomEvent("GSProfileEmailSettingsAdd",!0,!0,a);return b}function GSProfileEmailSettingsAdd(a){this.elem=a;this.input=a.getElementsByTagName("input")[0];this.input.addEventListener("keyup",this.inputChanged.bind(this));this.button=a.getElementsByTagName("button")[0];this.button.setAttribute("disabled","disabled");this.button.addEventListener("click",this.addClicked.bind(this))}
GSProfileEmailSettingsAdd.prototype.inputChanged=function(a){0<this.input.value.length&&this.button.hasAttribute("disabled")&&(!("validity"in this.input)||this.input.validity.valid)?this.button.removeAttribute("disabled"):"Enter"==a.key&&!this.button.hasAttribute("disabled")?this.button.click():(!this.button.hasAttribute("disabled")&&0==this.input.value.length||"validity"in this.input&&!this.input.validity.valid)&&this.button.setAttribute("disabled","disabled")};
GSProfileEmailSettingsAdd.prototype.addClicked=function(a){var b=null;this.input.setAttribute("disabled","disabled");b=GSProfileEmailSettingsAddEvent({email:this.input.value});a.target.dispatchEvent(b)};GSProfileEmailSettingsAdd.prototype.reset=function(){this.input.value="";this.input.removeAttribute("disabled")};
function GSProfileEmailSettingsUpdate(a,b,c,d,l,m){function r(b){var a=null,a=JSON.parse(b.target.responseText);s(a)}function s(a){n.update(a);p.update(a);w.update(a)}function t(a){h.remove(a.detail.email,e)}function u(a){h.prefer(a.detail.email,e)}function v(a){h.demote(a.detail.email,e)}function y(a){h.resend(a.detail.email,e)}function e(a){var b=null,b=JSON.parse(a.target.responseText);q.display(b.message);s(b.email)}function k(a){h.add(a.detail.email,z)}function z(a){a=null;a=JSON.parse(this.responseText);
q.display(a.message,q.SUCCESS);s(a.email);x.reset()}var h=null,n=null,p=null,w=null,q=null,x=null;(function(){var f=null,e=null,g=f=null,g=null;q=new GSProfileEmailSettingsMessage(m);g=document.querySelector(l);f=document.querySelector(a);f.addEventListener("GSProfileEmailSettingsRemove",t);f.addEventListener("GSProfileEmailSettingsPrefer",u);f.addEventListener("GSProfileEmailSettingsDemote",v);n=new GSProfileEmailSettingsPreferred(f,g);e=document.querySelector(b);e.addEventListener("GSProfileEmailSettingsRemove",
t);e.addEventListener("GSProfileEmailSettingsPrefer",u);e.addEventListener("GSProfileEmailSettingsDemote",v);p=new GSProfileEmailSettingsExtra(e,g);f.addEventListener("GSProfileEmailDragStart",function(a){p.dropPrepare()});f.addEventListener("GSProfileEmailDragEnd",function(a){p.clearDropPrepare()});e.addEventListener("GSProfileEmailDragStart",function(a){n.dropPrepare()});e.addEventListener("GSProfileEmailDragEnd",function(a){n.clearDropPrepare()});f=document.querySelector(c);f.addEventListener("GSProfileEmailSettingsRemove",
t);f.addEventListener("GSProfileEmailSettingsResend",y);w=new GSProfileEmailSettingsUnverified(f,g);g=document.querySelector(d);x=new GSProfileEmailSettingsAdd(g);g.addEventListener("GSProfileEmailSettingsAdd",k);h=new GSProfileEmailSettingsAJAX;h.status(r)})()}
window.addEventListener("load",function(a){a=null;a=document.getElementById("gs-profile-email-settings-script");GSProfileEmailSettingsUpdate(a.getAttribute("data-preferred"),a.getAttribute("data-extra"),a.getAttribute("data-unverified"),a.getAttribute("data-add"),a.getAttribute("data-model"),a.getAttribute("data-messagebox"))});
